### PR TITLE
Added Samson profile

### PR DESCRIPTION
**Pull request by Samson063**
Added Samson profile

### CODE REVIEW

**Comment by OSCA-Ado-Ekiti** [comment]
There is a conflict, kindly resolve it by updating your repository to be in sync with OSCA's main branch then resolve the conflicts then create another pull request.

**Comment by Victorayo** [comment]
You can reach out to me Samson , if you're able to do this at second attempt

**Comment by Samson063** [comment]
conflict resolved

**Review by Samson063 — COMMENTED** [review]
conflict resolved

**Pull request merged**
